### ISSUE TITLE
Sync credentials with docker-machine

### ISSUE THREAD

**Issue by finnweiler** [MohamedKari/awsenv#3]
The temporary credentials stored in `./awsenv/sessions.json` won't be synced to `./docker/machine/machines/<your-machine>/config.json`. Therefore as soon as your temporary credentials expire you have to manually update the corresponding docker machine config.

**Comment by MohamedKari** [comment]
AWS Credentials
If you are using temporary session credentials obtained from an IAM role assumption as I am doing, you will notice that after the credentials used to create the docker-machine expire, docker-machine will throw a 400 error with the info, “RequestExpired: Request has expired”. Unfortunately, docker-machine has stored the initial credentials in the ~/.docker/machine/machines/docker-ml/config.json and they take precedence over any AWS credentials set in the environment. However, there is an easy fix: edit the config.json and remove the lines, containing the Access Key ID, the Secret Access Key, and Session Token. From now on, commands issued to docker-machine will resort to the environment variables. 

Source: https://blog.mkari.de/posts/remote-docker-for-ml/
